/**
 * Meta-Agent Orchestration System Types
 * 
 * This module defines the types for the meta-agent system that analyzes
 * user blueprints and distributes work to 18 specialized Composers.
 */

/**
 * The 18 Composer module identifiers
 */
export type ComposerModuleId =
  | 'UI-Kit'
  | 'UI-Pages'
  | 'API-Routes'
  | 'API-Integration'
  | 'Database'
  | 'Auth'
  | 'Billing'
  | 'Analytics'
  | 'QA-Testing'
  | 'Debug'
  | 'Security'
  | 'Performance'
  | 'DevOps'
  | 'Documentation'
  | 'Localization'
  | 'Notifications'
  | 'Search'
  | 'Monitoring';

/**
 * Output types that Composers can produce
 */
export type OutputType = 
  | 'code-snippet'
  | 'markdown-plan'
  | 'config-file'
  | 'architecture-diagram'
  | 'test-suite'
  | 'documentation';

/**
 * Tech stack options
 */
export type TechStackItem =
  | 'Next.js'
  | 'TailwindCSS'
  | 'Framer Motion'
  | 'TypeScript'
  | 'React'
  | 'Node.js'
  | 'PostgreSQL'
  | 'Prisma'
  | 'NextAuth'
  | 'Stripe'
  | 'shadcn/ui'
  | 'Zustand'
  | 'React Query'
  | 'Axios'
  | 'Jest'
  | 'Vitest';

/**
 * User's SaaS Blueprint input
 */
export interface Blueprint {
  /** Unique identifier for the blueprint */
  id: string;
  /** Name of the SaaS project */
  name: string;
  /** Full description of the SaaS functionality */
  description: string;
  /** Target features list */
  features: string[];
  /** Technology preferences */
  techPreferences?: TechStackItem[];
  /** Design preferences */
  designPreferences?: {
    colorScheme?: string;
    typography?: string;
    style?: string;
  };
  /** Created timestamp */
  createdAt: Date;
}

/**
 * Prompt task sent to a Composer
 */
export interface PromptTask {
  /** Module identifier */
  module_id: ComposerModuleId;
  /** Goal description for this module */
  goal: string;
  /** Technology stack to use */
  tech_stack: TechStackItem[];
  /** Expected output type */
  output_type: OutputType;
  /** Constraints and requirements */
  constraints: string[];
  /** References from the user's blueprint */
  references: string;
  /** Priority level (1-18) */
  priority: number;
  /** Dependencies on other modules */
  dependencies: ComposerModuleId[];
}

/**
 * Output from a Composer
 */
export interface ComposerOutput {
  /** Module identifier */
  module_id: ComposerModuleId;
  /** Status of the task */
  status: 'pending' | 'in-progress' | 'completed' | 'failed';
  /** Generated content */
  content: string;
  /** Type of output produced */
  output_type: OutputType;
  /** Execution time in milliseconds */
  executionTime?: number;
  /** Error message if failed */
  error?: string;
  /** Generated files */
  files?: GeneratedFile[];
}

/**
 * A file generated by a Composer
 */
export interface GeneratedFile {
  /** File path */
  path: string;
  /** File content */
  content: string;
  /** File type */
  type: 'component' | 'api' | 'config' | 'test' | 'documentation' | 'style';
}

/**
 * Consistency review result
 */
export interface ConsistencyReview {
  /** Overall consistency score (0-100) */
  score: number;
  /** Issues found */
  issues: ConsistencyIssue[];
  /** Dependencies validated */
  dependenciesValid: boolean;
  /** Naming conventions consistent */
  namingConsistent: boolean;
  /** Style consistency */
  styleConsistent: boolean;
}

/**
 * A consistency issue
 */
export interface ConsistencyIssue {
  /** Severity level */
  severity: 'error' | 'warning' | 'info';
  /** Module where issue was found */
  module_id: ComposerModuleId;
  /** Issue description */
  description: string;
  /** Suggestion for fixing */
  suggestion?: string;
}

/**
 * Aggregated Blueprint (final output)
 */
export interface AggregatedBlueprint {
  /** Original blueprint ID */
  blueprintId: string;
  /** Processing round number */
  round: number;
  /** Timestamp */
  timestamp: Date;
  /** All composer outputs */
  outputs: ComposerOutput[];
  /** Consistency review results */
  consistencyReview: ConsistencyReview;
  /** Module summaries */
  moduleSummaries: ModuleSummary[];
  /** Dependency graph */
  dependencyGraph: DependencyNode[];
  /** Suggested implementation order */
  implementationOrder: ComposerModuleId[];
  /** Overall status */
  status: 'incomplete' | 'needs-revision' | 'complete';
}

/**
 * Summary of a module
 */
export interface ModuleSummary {
  /** Module identifier */
  module_id: ComposerModuleId;
  /** Brief summary */
  summary: string;
  /** Completion percentage */
  completionPercentage: number;
  /** Files generated count */
  filesGenerated: number;
}

/**
 * Dependency graph node
 */
export interface DependencyNode {
  /** Module identifier */
  module_id: ComposerModuleId;
  /** Dependencies */
  dependsOn: ComposerModuleId[];
  /** Modules that depend on this one */
  requiredBy: ComposerModuleId[];
}

/**
 * Workflow state
 */
export interface WorkflowState {
  /** Current phase */
  phase: 'parsing' | 'distributing' | 'composing' | 'collecting' | 'reviewing' | 'aggregating' | 'complete';
  /** Current round number */
  round: number;
  /** Original blueprint */
  blueprint: Blueprint;
  /** Generated prompt tasks */
  promptTasks: PromptTask[];
  /** Composer outputs */
  outputs: ComposerOutput[];
  /** Final aggregated result */
  aggregatedBlueprint?: AggregatedBlueprint;
}
